version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: <%= appName %>
    environment:
      - APP_HOST=<%= hostname %>
      - APP_PORT=<%= port %>
      - DATABASE_URL=<%= databaseUrl %>
      - DATABASE_SCHEMA=<%= dbSchema %>
      - DATABASE_SSL=<%= ssl || 'false' %>
      - DATABASE_ENCRYPT=<%= encrypt || 'false' %>
      - AUTH_SECRET=<%= authSecret %>
    ports:
      - "<%= port %>:<%= port %>"
    volumes:
      - ./:/usr/src/app
