version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: <%= appName %>
    environment:
      - APPLICATION_HOST=<%= hostname || 'http://localhost' %>
      - APPLICATION_PORT=<%= port || 3000 %>
      - DATABASE_URL=<%= databaseUrl %>
      - DATABASE_SCHEMA=<%= dbSchema || 'public' %>
      - DATABASE_SSL=<%= ssl || 'false' %>
      - DATABASE_ENCRYPT=<%= encrypt || 'false' %>
      - AUTH_SECRET=<%= authSecret %>
    ports:
      - "<%= port %>:<%= port %>"
    volumes:
      - ./:/usr/src/app
